### ISSUE TITLE
Add licensing information

### ISSUE THREAD

**Issue by akien-mga** [Nooskewl/monster#2]
According to the source files header [1], the game is under the [BSD 3-Clause License](http://opensource.org/licenses/BSD-3-Clause). It would be nice to make this easier to find by putting the license text in a LICENSE.txt file at the root of the repo.

Even if it's redundant, you could probably also specify that the code files are under the BSD 3-Clause License in the README.md that I just proposed in a pull request. It would also be nice to specify the license of the data files and give attribution to the artist(s).

[1] https://github.com/Nooskewl/monster/blob/master/src/monster.cpp

**Comment by akien-mga** [comment]
Note that in the license header that you are using currently, there are occurrences of ```<organization>``` and ```<copyright holder>```. The current official text of the BSD 3-Clause License is a bit better, as it states instead ```copyright holder``` and ```THE COPYRIGHT HOLDERS AND CONTRIBUTORS``` respectively, which avoids the need to fill in the blanks.

**Comment by trentg** [comment]
Done, thanks again!

**Comment by akien-mga** [comment]
I would have kept the licensing information in the source files headers, but I guess it's working too if it's only in a LICENSE.txt file.
